[package]
name = "decimator-gtk4"
version = "0.1.0"
authors = ["Malcolm Ramsay <m@malramsay.com>"]
edition = "2021"
publish = false

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
gtk = {package="gtk4", version="*", features = ['v4_6']}
walkdir = "2.3.2"
anyhow = "1.0.65"
rayon = "1.5.3"
once_cell = "*"
image = "0.24.5"
log = "0.4.17"
adw = { version = "0.2.1", package = "libadwaita", features = ["gtk_v4_6"] }
tracing-bunyan-formatter = "0.3.4"
tracing-log = "0.1.3"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.23.0", features = ["tracing"] }
uuid = { version = "1.2.2", features = ["v4", "serde"] }
sqlx = {version = "0.6", features= ["runtime-tokio-rustls", "sqlite", "uuid", "time", "migrate", "macros"]}
camino = { version = "1.1.1", features = ["serde1"] }

[build-dependencies]
glib-build-tools = "0.16.3"


