[package]
name = "decimator-gtk4"
version = "0.1.0"
authors = ["Malcolm Ramsay <m@malramsay.com>"]
edition = "2021"
publish = false

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-bunyan-formatter = "0.3.4"
tracing-log = "0.1.3"
walkdir = "2.3.2"
anyhow = "1.0.65"
# rayon = "1.5.3"
# once_cell = "*"
log = "0.4.17"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
# tokio = { version = "1.23.0", features = ["tracing"] }
uuid = { version = "1.2.2", features = ["v4", "serde"] }
sqlx = {version = "0.6", features= ["runtime-tokio-rustls", "sqlite", "uuid", "time", "migrate", "macros"]}
camino = { version = "1.1.1", features = ["serde1"] }
time = {version = "0.3.17", features = ["serde"] }
kamadak-exif = "0.5.5"
itertools = "0.10.5"
relm4 = { git="https://github.com/malramsay64/Relm4", branch="list-view-wrapper", features = ["macros", "gnome_43", "libadwaita"] }
image = "0.24.6"
futures = "0.3.28"
num_cpus = "1.15.0"
relm4-components = { git="https://github.com/malramsay64/Relm4", branch="list-view-wrapper" }
