[package]
name = "decimator"
version = "0.1.0"
authors = ["Malcolm Ramsay <m@malramsay.com>"]
edition = "2021"
publish = false

[dependencies]
relm4-components = { git="https://github.com/Relm4/Relm4" }
relm4-icons = { version = "0.6.0-beta.6", features = ["window-scrolling", "grid-large", "plus", "minus"] }
image = "~0.24.6"
kamadak-exif = "~0.5.5"
sea-orm = {version="~0.11.3", features = ["sqlx-sqlite", "runtime-tokio-rustls", "with-time"]}
uuid = { version = "~1.2.2", features = ["v4", "serde"] }
camino = { version = "~1.1.1", features = ["serde1"] }
time = {version = "~0.3.17", features = ["serde"] }
tracing = "~0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-bunyan-formatter = "0.3.4"
tracing-log = "0.1.3"
walkdir = "~2.3.2"
anyhow = "~1.0.65"
log = "~0.4.17"
serde = { version = "~1.0.150", features = ["derive"] }
serde_json = "1.0.89"
futures = "0.3.28"
num_cpus = "1.15.0"
itertools = "~0.10.5"
iced = { version = "0.9.0", features = ["image", "tokio"] }
dirs = "5.0.1"
tokio = "1.29.1"
diesel = { version = "2.1.0", features = ["sqlite", "uuid", "time"] }
diesel-derive-enum = { version = "2.1.0", features = ["sqlite"] }
