[package]
name = "facial-recognition"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
burn.workspace = true
floatconv = "0.2.8"
num = "0.4.3"

[dev-dependencies]
approx = "0.5.1"
# burn-import = "0.14"
csv = "1.3.0"
image = "0.25.1"
